<style>
    /* Main styling and responsive adjustments */
    @import url(https://fonts.googleapis.com/css?family=Open+Sans);

    body {
        font-family: "Open Sans", sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f5f5f5;
    }

    .container {
        width: 100%;
        max-width: 430px;
        height: auto;
        margin: 0 auto;
        position: relative;
        text-align: center;
    }

    /* Card styling */
    .card {
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        overflow: hidden;
        width: 90%;
        max-width: 700px;
        margin: 20px auto;
        transition: transform 0.2s ease, box-shadow 0.2s ease;
    }

    .card:hover {
        transform: scale(1.05);
        box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
    }

    /* Responsive adjustments */
    @media (max-width: 768px) {
        .container {
            max-width: 90%;
        }

        /* Ensure SVG scales for mobile screens */
        svg {
            width: 80%; /* Set SVG to occupy 80% of the container */
            max-width: 300px; /* Maximum width on mobile screens */
            height: auto;
        }
    }

    /* Additional mobile adjustments for smaller screens */
    @media (max-width: 480px) {
        .container {
            max-width: 100%;
        }

        svg {
            width: 80%; /* Maintain 80% width on small devices */
            max-width: 300px;
            height: auto;
        }
    }
</style>

<body>
    <div class="card">
        <div class="score-band-wrapper" style="color: #e00f0fcc;font-weight: 800;text-align: center; font-size:18px;">
            Your CreditLab score is <span class="score-band-label">Excellent</span>
        </div>
        <div class="container">
            <svg height="400px" width="400px" viewBox="0 0 400 400">
                <!-- Circle Elements for Score Indicator -->
                <circle id="red" fill="none" stroke="#bd2727" stroke-width="30" cx="200" cy="200" r="140"
                    stroke-dasharray="150, 747" stroke-dashoffset="597" />
                <circle class="grey greyRed" fill="none" stroke="#F1F1F1" stroke-width="30" cx="200" cy="200" r="140"
                    stroke-dasharray="150, 747" stroke-dashoffset="597" />
                <circle id="orange" fill="none" stroke="#f79a38" stroke-width="30" cx="200" cy="200" r="140"
                    stroke-dasharray="150, 747" stroke-dashoffset="447" />
                <circle class="grey greyOrange" fill="none" stroke="#F1F1F1" stroke-width="30" cx="200" cy="200" r="140"
                    stroke-dasharray="150, 747" stroke-dashoffset="447" />
                <circle id="yellow" fill="none" stroke="#fadd00" stroke-width="30" cx="200" cy="200" r="140"
                    stroke-dasharray="150, 747" stroke-dashoffset="297" />
                <circle class="grey greyYellow" fill="none" stroke="#F1F1F1" stroke-width="30" cx="200" cy="200" r="140"
                    stroke-dasharray="150, 747" stroke-dashoffset="297" />
                <circle id="light-green" fill="none" stroke="#91c738" stroke-width="30" cx="200" cy="200" r="140"
                    stroke-dasharray="150, 747" stroke-dashoffset="147" />
                <circle class="grey greyLightGreen" fill="none" stroke="#F1F1F1" stroke-width="30" cx="200" cy="200" r="140"
                    stroke-dasharray="150, 747" stroke-dashoffset="147" />
                <circle id="green" fill="none" stroke="#1f9c4c" stroke-width="30" cx="200" cy="200" r="140"
                    stroke-dasharray="150, 747" stroke-dashoffset="0" />
                <circle class="grey greyGreen" fill="none" stroke="#F1F1F1" stroke-width="30" cx="200" cy="200" r="140"
                    stroke-dasharray="150, 747" stroke-dashoffset="0" />
            </svg>
            <div class="score-dial-wrapper">
                Your CreditLab score is <span style="font-size:20px;font-weight: 900;" class="score-dial-value"><?=$creditlab_score?></span>
            </div>
        </div>
        <p class="card-content card" style="padding: 25px;">Increase your Creditlab score by making timely payments on or before due date. There by your limit gets increased</p>
        <p class="card-content card" style="padding: 25px;">The CreditLab score is generated by conducting a credit risk evaluation on the provided data, utilizing an internal scoring system.</p>
        <p style="color: #e00f0fcc;font-weight: 800;text-align: center;">Note : This score might differ from the scores provided by your credit bureau.</p>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        const radius = 140;
        const circumference = 2 * Math.PI * radius; // 879.2
        const customCircumference = circumference * 0.85; // 747.32
        const arcLength = customCircumference / 5; // 149.46
        const offset = arcLength * 5;

        /* Updated minimum, maximum values and length for the new 350-900 range */
        const redArc = {
            min: 350.00,
            max: 479.00,
            length: 129.00
        };
        const orangeArc = {
            min: 480.00,
            max: 599.00,
            length: 119.00
        };
        const yellowArc = {
            min: 600.00,
            max: 719.00,
            length: 119.00
        };
        const lightGreenArc = {
            min: 720.00,
            max: 839.00,
            length: 119.00
        };
        const greenArc = {
            min: 840.00,
            max: 900.00,
            length: 60.00
        };

        $(document).ready(function () {
            var scoreBandLabel = $(".score-band-label");
            var score = <?=$creditlab_score?>;

            $(".score-dial-value").html(score);

            if (score >= redArc.min) {
                scoreBandLabel.html("Very Poor");
                $(".greyRed").attr("stroke-dasharray",
                    arcLength + "," + (customCircumference + ((arcLength * (score - redArc.min)) / redArc.length)));
            }

            if (score >= orangeArc.min) {
                scoreBandLabel.html("Poor");
                $(".greyOrange").attr("stroke-dasharray",
                    arcLength + "," + (customCircumference + ((arcLength * (score - orangeArc.min)) / orangeArc.length)));
            }

            if (score >= yellowArc.min) {
                scoreBandLabel.html("Fair");
                $(".greyYellow").attr("stroke-dasharray",
                    arcLength + "," + (customCircumference + ((arcLength * (score - yellowArc.min)) / yellowArc.length)));
            }

            if (score >= lightGreenArc.min) {
                scoreBandLabel.html("Good");
                $(".greyLightGreen").attr("stroke-dasharray",
                    arcLength + "," + (customCircumference + ((arcLength * (score - lightGreenArc.min)) / lightGreenArc.length)));
            }

            if (score >= greenArc.min) {
                scoreBandLabel.html("Excellent");
                let greenArchCalc = ((arcLength * (score - greenArc.min)) / greenArc.length);
                $(".greyGreen").attr("stroke-dasharray", (arcLength - greenArchCalc) + "," + customCircumference);
                $('.greyGreen').attr("stroke-dashoffset", -greenArchCalc);
            }
        });
    </script>